name: bloom_cli
description: The official command-line interface for the Bloom application framework.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

executables:
  bloom: bloom

dependencies:
  args: ^2.5.0
  path: ^1.9.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.0
  xml: ^6.5.0
  qr: ^3.0.2
  http: ^1.2.0
  http_parser: ^4.0.2
  archive: ^3.6.1
  image: ^4.3.0

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
