// lib/src/lint/bloom_lint.dart
import 'dart:io';
import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/visitor.dart';
import 'package:analyzer/source/line_info.dart';
import 'package:path/path.dart' as p;
import '../utils/project.dart';

class LintFinding {
  final String filePath;
  final int lineNumber;
  final String ruleName;
  final String message;
  final String snippet;

  LintFinding({
    required this.filePath,
    required this.lineNumber,
    required this.ruleName,
    required this.message,
    required this.snippet,
  });
}

class LintResult {
  final List<LintFinding> findings;
  final int scannedFilesCount;

  LintResult({required this.findings, required this.scannedFilesCount});

  bool get hasFindings => findings.isNotEmpty;
}

/// Bloom-specific lint rules for `bloom_js_native` projects, grounded in the
/// pitfalls documented in COOKBOOK.md Section 20.
class BloomLinter {
  final BloomProject project;

  BloomLinter(this.project);

  static final RegExp _handAuthoredStyleOrLink = RegExp(
    r'<(style)\b|<link[^>]*\brel=["\x27]stylesheet["\x27]',
    caseSensitive: false,
  );

  LintResult lint() {
    final root = project.rootDir.path;
    final findings = <LintFinding>[];
    int scanned = 0;

    for (final dirName in ['lib', 'test', 'bin']) {
      final dir = Directory(p.join(root, dirName));
      if (!dir.existsSync()) continue;

      for (final file in dir.listSync(recursive: true, followLinks: false)) {
        if (file is! File || !file.path.endsWith('.dart')) continue;
        // Generated bindings from `bloom add npm:<pkg>` are not hand-authored;
        // skip them so lint never flags code developers didn't write.
        if (p.isWithin(p.join(root, 'lib', 'src', 'plugins'), file.path)) continue;

        scanned++;
        final relPath = p.relative(file.path, from: root).replaceAll('\\', '/');
        final content = file.readAsStringSync();
        findings.addAll(lintDartSource(content, filePath: relPath));
      }
    }

    final indexHtml = File(p.join(root, 'web', 'index.html'));
    if (indexHtml.existsSync() && _isWebDomTarget()) {
      scanned++;
      final relPath = p.relative(indexHtml.path, from: root).replaceAll('\\', '/');
      final content = indexHtml.readAsStringSync();
      findings.addAll(lintHtmlSource(content, filePath: relPath, isWebDom: true));
    }

    return LintResult(findings: findings, scannedFilesCount: scanned);
  }

  bool _isWebDomTarget() {
    if (!project.bloomYamlFile.existsSync()) return false;
    final content = project.bloomYamlFile.readAsStringSync();
    return content.contains('target: web_dom') || content.contains('target: "web_dom"');
  }

  /// Lints a Dart source string using analyzer parse-only AST traversal.
  static List<LintFinding> lintDartSource(String source, {String filePath = 'lib/main.dart'}) {
    final parseResult = parseString(content: source, throwIfDiagnostics: false);
    final visitor = _BloomLintVisitor(
      filePath: filePath,
      lineInfo: parseResult.lineInfo,
      source: source,
    );
    parseResult.unit.accept(visitor);
    return visitor.findings;
  }

  /// Lints web/index.html content for non-SSR/non-Dart stylesheet/style tags.
  static List<LintFinding> lintHtmlSource(
    String source, {
    String filePath = 'web/index.html',
    bool isWebDom = true,
  }) {
    if (!isWebDom) return [];
    final findings = <LintFinding>[];
    final lines = source.split('\n');

    for (var i = 0; i < lines.length; i++) {
      final line = lines[i];
      if (line.contains('AUTO-GENERATED by bloom_cli')) continue;
      if (_handAuthoredStyleOrLink.hasMatch(line)) {
        findings.add(LintFinding(
          filePath: filePath,
          lineNumber: i + 1,
          ruleName: 'hand_authored_style_in_index_html',
          message:
              'web/index.html should stay near-empty (meta tags, SEO content, and the main.js '
              'script only). Design tokens belong in lib/design/tokens.dart injected via '
              'Style(), and fonts should be wired with `bloom fonts optimize` + '
              'fontStylesheetLink() — see COOKBOOK.md Section 19.',
          snippet: line.trim(),
        ));
      }
    }

    return findings;
  }
}

class _BloomLintVisitor extends RecursiveAstVisitor<void> {
  final String filePath;
  final LineInfo lineInfo;
  final String source;
  final List<LintFinding> findings = [];

  static const Set<String> _inPlaceMutationMethods = {
    'add',
    'addAll',
    'remove',
    'removeAt',
    'removeLast',
    'removeWhere',
    'insert',
    'clear',
    'sort',
    'shuffle',
    'retainWhere',
  };

  static const Set<String> _eventParamNames = {
    'e',
    'ev',
    'evt',
    'event',
  };

  _BloomLintVisitor({
    required this.filePath,
    required this.lineInfo,
    required this.source,
  });

  String _getSnippet(AstNode node) {
    final lineNumber = lineInfo.getLocation(node.offset).lineNumber;
    final lineStarts = lineInfo.lineStarts;
    final lineStart = lineStarts[lineNumber - 1];
    final lineEnd = lineNumber < lineStarts.length ? lineStarts[lineNumber] - 1 : source.length;
    return source.substring(lineStart, lineEnd).trim();
  }

  // 1. nullable_event_force_unwrap
  @override
  void visitPostfixExpression(PostfixExpression node) {
    super.visitPostfixExpression(node);

    if (node.operator.lexeme != '!') return;

    final operand = node.operand;
    String? propName;
    String? receiverName;

    if (operand is PropertyAccess) {
      propName = operand.propertyName.name;
      final target = operand.realTarget;
      if (target is SimpleIdentifier) {
        receiverName = target.name;
      }
    } else if (operand is PrefixedIdentifier) {
      propName = operand.identifier.name;
      receiverName = operand.prefix.name;
    }

    if (propName != 'value' && propName != 'checked') return;
    if (receiverName == null) return;

    // Parse-only syntactic heuristic for BloomEvent receivers (type resolution unavailable without package_config).
    if (_isEnclosingEventParam(node, receiverName)) {
      findings.add(LintFinding(
        filePath: filePath,
        lineNumber: lineInfo.getLocation(node.offset).lineNumber,
        ruleName: 'nullable_event_force_unwrap',
        message:
            'BloomEvent.value and BloomEvent.checked are both nullable (String?/bool?) — '
            'force-unwrapping with `!` will throw at runtime on events where the field is '
            'legitimately null (e.g. non-input targets). Use `e.value ?? ""` or a null check.',
        snippet: _getSnippet(node),
      ));
    }
  }

  bool _isEnclosingEventParam(AstNode node, String name) {
    AstNode? current = node.parent;
    while (current != null) {
      FormalParameterList? params;
      if (current is FunctionExpression) {
        params = current.parameters;
      } else if (current is MethodDeclaration) {
        params = current.parameters;
      } else if (current is FunctionDeclaration) {
        params = current.functionExpression.parameters;
      }

      if (params != null) {
        for (final p in params.parameters) {
          final paramName = p.name?.lexeme;
          if (paramName == name) {
            // Check type annotation if present
            if (p is SimpleFormalParameter && p.type != null) {
              final typeStr = p.type!.toSource();
              if (typeStr.contains('BloomEvent')) return true;
              return false;
            }
            if (p is DefaultFormalParameter) {
              final normal = p.parameter;
              if (normal is SimpleFormalParameter && normal.type != null) {
                final typeStr = normal.type!.toSource();
                if (typeStr.contains('BloomEvent')) return true;
                return false;
              }
            }
            // If untyped, match conventional event parameter names
            if (_eventParamNames.contains(name)) {
              return true;
            }
            return false;
          }
        }
      }
      current = current.parent;
    }
    return false;
  }

  // 2. foreach_missing_key
  // 4. live_never_reads_signal
  @override
  void visitInstanceCreationExpression(InstanceCreationExpression node) {
    super.visitInstanceCreationExpression(node);
    _checkForEachAndLive(
      typeName: node.constructorName.type.name2.lexeme,
      argumentList: node.argumentList,
      anchor: node,
    );
  }

  void _checkForEachAndLive({
    required String typeName,
    required ArgumentList argumentList,
    required AstNode anchor,
  }) {
    if (typeName == 'ForEach') {
      final hasKey = argumentList.arguments.any(
        (a) => a is NamedExpression && a.name.label.name == 'key',
      );
      if (!hasKey) {
        findings.add(LintFinding(
          filePath: filePath,
          lineNumber: lineInfo.getLocation(anchor.offset).lineNumber,
          ruleName: 'foreach_missing_key',
          message:
              'ForEach<T>(...) without a `key:` extractor will use index-based reconciliation, '
              'which misattributes state (e.g. focus, form input) when the list reorders. '
              'Pass `key: (item) => item.id` or similar.',
          snippet: _getSnippet(anchor),
        ));
      }
    }

    if (typeName == 'Live') {
      FunctionExpression? builder;
      for (final arg in argumentList.arguments) {
        if (arg is FunctionExpression) {
          builder = arg;
          break;
        } else if (arg is NamedExpression && arg.expression is FunctionExpression) {
          builder = arg.expression as FunctionExpression;
          break;
        }
      }

      if (builder != null) {
        final signalChecker = _SignalValueReadChecker();
        builder.body.accept(signalChecker);
        if (!signalChecker.hasSignalValueRead) {
          findings.add(LintFinding(
            filePath: filePath,
            lineNumber: lineInfo.getLocation(anchor.offset).lineNumber,
            ruleName: 'live_never_reads_signal',
            message:
                "Live(...) builder never reads any signal's .value property — "
                'Live creates a reactive subscription only when signals are accessed inside its builder. '
                "If this subtree is static, remove Live(...); if dynamic, access a signal's .value.",
            snippet: _getSnippet(anchor),
          ));
        }
      }
    }
  }

  // 3. browser_import_in_test
  @override
  void visitImportDirective(ImportDirective node) {
    super.visitImportDirective(node);

    final isTestFile = filePath.startsWith('test/') ||
        filePath.startsWith('test\\') ||
        p.split(filePath).contains('test');

    if (!isTestFile) return;

    final uri = node.uri.stringValue;
    if (uri != null && uri.endsWith('bloom_js_native/browser.dart')) {
      findings.add(LintFinding(
        filePath: filePath,
        lineNumber: lineInfo.getLocation(node.offset).lineNumber,
        ruleName: 'browser_import_in_test',
        message:
            "Importing 'package:bloom_js_native/browser.dart' in a test file requires a real DOM "
            '(dart test --platform chrome) and will fail under the default VM test runner. '
            "Import 'package:bloom_js_native/bloom_js_native.dart' (the SSR-safe core) instead "
            'unless this test is deliberately browser-only.',
        snippet: _getSnippet(node),
      ));
    }
  }

  // 5. inplace_signal_collection_mutation
  //
  // Also handles rules 2/4 (foreach_missing_key, live_never_reads_signal):
  // parse-only mode (no resolved element model) cannot tell a generic
  // function call apart from an implicit-`new` constructor call — analyzer
  // parses `ForEach<T>(...)`/`Live(...)` as MethodInvocation, not
  // InstanceCreationExpression, unless resolution is available. Both node
  // shapes must be checked so those rules actually fire on real Bloom code.
  @override
  void visitMethodInvocation(MethodInvocation node) {
    super.visitMethodInvocation(node);

    if (node.target == null) {
      _checkForEachAndLive(
        typeName: node.methodName.name,
        argumentList: node.argumentList,
        anchor: node,
      );
    }

    final methodName = node.methodName.name;
    if (!_inPlaceMutationMethods.contains(methodName)) return;

    final target = node.target;
    var targetHasValueProp = false;

    if (target is PropertyAccess) {
      targetHasValueProp = target.propertyName.name == 'value';
    } else if (target is PrefixedIdentifier) {
      targetHasValueProp = target.identifier.name == 'value';
    }

    if (targetHasValueProp) {
      findings.add(LintFinding(
        filePath: filePath,
        lineNumber: lineInfo.getLocation(node.offset).lineNumber,
        ruleName: 'inplace_signal_collection_mutation',
        message:
            "Mutating a signal's collection in place (e.g. `signal.value.add(...)`) does not notify "
            'subscribers because the identity of .value did not change. '
            'Reassign .value instead: `signal.value = [...signal.value, item]`.',
        snippet: _getSnippet(node),
      ));
    }
  }
}

class _SignalValueReadChecker extends RecursiveAstVisitor<void> {
  bool hasSignalValueRead = false;

  @override
  void visitPropertyAccess(PropertyAccess node) {
    if (node.propertyName.name == 'value') {
      hasSignalValueRead = true;
      return;
    }
    super.visitPropertyAccess(node);
  }

  @override
  void visitPrefixedIdentifier(PrefixedIdentifier node) {
    if (node.identifier.name == 'value') {
      hasSignalValueRead = true;
      return;
    }
    super.visitPrefixedIdentifier(node);
  }
}
