// lib/src/generator/fingerprint_generator.dart
import 'dart:convert';
import 'dart:io';
import 'package:crypto/crypto.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';
import '../utils/project.dart';

/// Generates runtime fingerprint metadata for the host project.
class FingerprintGenerator {
  final BloomProject project;

  FingerprintGenerator(this.project);

  /// Computes the canonical deterministic SHA-256 runtime fingerprint for this project.
  String computeFingerprint() {
    final buffer = StringBuffer();
    final config = project.loadBloomConfig();
    final bloomVersion = config['version']?.toString() ?? '1.0.0';
    final dartSdkVersion = Platform.version.split(' ').first;
    const flutterEngine = '3.27.0';

    buffer.writeln('bloom_version:$bloomVersion');
    buffer.writeln('flutter_engine:$flutterEngine');
    buffer.writeln('dart_sdk:$dartSdkVersion');

    // 1. Read module fingerprints from bloom.lock if available
    final lockFile = File(p.join(project.rootDir.path, 'bloom.lock'));
    if (lockFile.existsSync()) {
      try {
        final yaml = loadYaml(lockFile.readAsStringSync());
        if (yaml is YamlMap && yaml['native_modules'] is YamlMap) {
          final modules = yaml['native_modules'] as YamlMap;
          final sortedKeys = modules.keys.map((k) => k.toString()).toList()..sort();
          for (final k in sortedKeys) {
            final mod = modules[k];
            if (mod is YamlMap && mod['fingerprint'] != null) {
              buffer.writeln('module:$k:${mod['fingerprint']}');
            }
          }
        }
      } catch (_) {}
    }

    // 2. Read permissions/plugins from bloom.yaml
    final rawPerms = config['permissions'] ?? config['plugins'];
    final perms = <String>[];
    if (rawPerms is List) {
      for (final p in rawPerms) {
        perms.add(p.toString());
      }
    } else if (rawPerms is Map) {
      for (final k in rawPerms.keys) {
        perms.add(k.toString());
      }
    }

    final sortedPerms = perms..sort();
    for (final p in sortedPerms) {
      buffer.writeln('permission:$p');
    }

    return sha256.convert(utf8.encode(buffer.toString())).toString();
  }

  /// Emits lib/config/fingerprint.g.dart
  File generateFingerprintDart() {
    final configDir = Directory(p.join(project.rootDir.path, 'lib', 'config'))..createSync(recursive: true);
    final targetFile = File(p.join(configDir.path, 'fingerprint.g.dart'));
    final hash = computeFingerprint();

    final buffer = StringBuffer();
    buffer.writeln('// AUTO-GENERATED BY BLOOM CLI. DO NOT EDIT.');
    buffer.writeln('// Cryptographic native runtime fingerprint for OTA patch validation.');
    buffer.writeln();
    buffer.writeln("const String kBloomRuntimeFingerprint = '$hash';");
    buffer.writeln();

    targetFile.writeAsStringSync(buffer.toString());
    return targetFile;
  }
}
