// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Bloom CLI
// ignore_for_file: depend_on_referenced_packages, unused_import, file_names

import 'package:bloom_framework/bloom.dart';

import '../routes/index.dart';
import '../routes/settings.dart';
import '../routes/users/[id].dart';

final GoRouter appRouter = BloomRouter.create(
  initialLocation: '/',
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) {
        return const IndexRoute();
      },
    ),
    GoRoute(
      path: '/settings',
      builder: (context, state) {
        return const SettingsRoute();
      },
    ),
    GoRoute(
      path: '/users/:id',
      builder: (context, state) {
        return const UsersIdRoute();
      },
    ),
  ],
);
