name: bloom_framework
description: An opinionated application framework and developer platform built on Dart and Flutter.
version: 0.3.0
publish_to: none
homepage: https://bloom.dev
repository: https://github.com/bloom-framework/bloom
issue_tracker: https://github.com/bloom-framework/bloom/issues
topics:
  - framework
  - state-management
  - full-stack
  - mobile
  - flutter

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  crypto: ^3.0.3
  path: ^1.9.0
  signals: ^5.5.0
  signals_flutter: ^5.5.0
  go_router: ^14.8.0
  yaml: ^3.1.2
  meta: ^1.15.0
  http: ^1.2.0
  flutter_secure_storage: ^9.2.2
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.3
  image_picker: ^1.1.2
  shorebird_code_push: ^2.0.7
  supabase_flutter: ^2.17.1
  web: ^1.1.0
  bloom_js_native:
    path: ../bloom_js_native
  bloom_seo:
    path: ../bloom_seo

dev_dependencies:
  flutter_lints: ^5.0.0
