name: bloom_fullstack_api
description: Bloom Official Full-Stack API & Web SSR Reference Application
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  bloom_framework:
    path: ../../packages/bloom_framework

dev_dependencies:
  flutter_test:
    sdk: flutter
