name: bloom_migrate
description: Database migrations CLI and library for Bloom applications using bloom_db.
version: 0.1.1
repository: https://github.com/Chidi09/Bloom
issue_tracker: https://github.com/Chidi09/Bloom/issues
topics:
  - bloom
  - orm
  - database
  - migrations

environment:
  sdk: '>=3.3.0 <4.0.0'

executables:
  bloom_migrate: bloom_migrate

dependencies:
  args: ^2.5.0
  path: ^1.9.0
  meta: ^1.15.0
  bloom_db: ^0.1.0

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0
