// test/web/tailwind_static_build_test.dart
import 'dart:io';
import 'package:args/command_runner.dart';
import 'package:bloom_cli/src/commands/build_command.dart';
import 'package:bloom_cli/src/utils/project.dart';
import 'package:bloom_cli/src/web/tailwind_static_build.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  group('TailwindStaticBuild', () {
    late Directory tempDir;

    setUp(() {
      tempDir = Directory.systemTemp.createTempSync('bloom_tw_test_');
      final pubspec = File(p.join(tempDir.path, 'pubspec.yaml'));
      pubspec.writeAsStringSync('name: tw_test_app\n');
      final libDir = Directory(p.join(tempDir.path, 'lib'))..createSync(recursive: true);
      File(p.join(libDir.path, 'main.dart')).writeAsStringSync('void main() {}');
      Directory(p.join(tempDir.path, 'web')).createSync(recursive: true);
    });

    tearDown(() {
      if (tempDir.existsSync()) {
        try {
          tempDir.deleteSync(recursive: true);
        } catch (_) {}
      }
    });

    test('is a silent true no-op for non-Tailwind projects', () async {
      final bloomYaml = File(p.join(tempDir.path, 'bloom.yaml'));
      bloomYaml.writeAsStringSync('''
name: non_tailwind_app
target: web_dom
npm_packages:
  canvas-confetti:
    version: 1.9.4
''');

      final project = BloomProject.fromDirectory(tempDir);
      final builder = TailwindStaticBuild(project: project);

      expect(builder.isTailwindProject, isFalse);

      final exitCode = await builder.build();
      expect(exitCode, 0);

      // Verify no CSS file or .dart_tool entry was written
      final distCss = File(p.join(tempDir.path, 'web', 'dist', 'app.css'));
      expect(distCss.existsSync(), isFalse);

      final entryCss = File(p.join(tempDir.path, '.dart_tool', 'bloom', 'tailwind_entry.css'));
      expect(entryCss.existsSync(), isFalse);
    });

    test('fails with non-zero exit code when Bun is missing', () async {
      final bloomYaml = File(p.join(tempDir.path, 'bloom.yaml'));
      bloomYaml.writeAsStringSync('''
name: tailwind_app
target: web_dom
npm_packages:
  "@tailwindcss/browser":
    version: 4.3.3
''');

      final project = BloomProject.fromDirectory(tempDir);
      final builder = TailwindStaticBuild(
        project: project,
        hasBunCheck: () => false, // Simulate Bun missing
      );

      expect(builder.isTailwindProject, isTrue);

      final exitCode = await builder.build();
      expect(exitCode, 1);

      final distCss = File(p.join(tempDir.path, 'web', 'dist', 'app.css'));
      expect(distCss.existsSync(), isFalse);
    });

    test('fails and surfaces CLI error on malformed/failing Tailwind input CSS', () async {
      final bloomYaml = File(p.join(tempDir.path, 'bloom.yaml'));
      bloomYaml.writeAsStringSync('''
name: tailwind_app
target: web_dom
npm_packages:
  "@tailwindcss/browser":
    version: 4.3.3
''');

      // Create an invalid/malformed hand-authored CSS file
      final userCss = File(p.join(tempDir.path, 'web', 'tailwind.css'));
      userCss.writeAsStringSync('@invalid_unclosed_block {\n');

      final project = BloomProject.fromDirectory(tempDir);
      final builder = TailwindStaticBuild(project: project);

      final exitCode = await builder.build();
      expect(exitCode, isNot(0));
    });

    test('produces real static minified CSS and preserves source-of-truth index.html', () async {
      final bloomYaml = File(p.join(tempDir.path, 'bloom.yaml'));
      bloomYaml.writeAsStringSync('''
name: tailwind_app
target: web_dom
npm_packages:
  "@tailwindcss/browser":
    version: 4.3.3
''');

      // Create a Dart file using Tailwind classes
      final componentDart = File(p.join(tempDir.path, 'lib', 'button.dart'));
      componentDart.writeAsStringSync('''
void renderButton() {
  final className = 'bg-indigo-600 hover:bg-indigo-500 text-white rounded-full px-4 py-2';
}
''');

      // Create source-of-truth web/index.html with dev-mode JIT tag
      final originalHtmlContent = '''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Tailwind Test</title>
  <script type="module">
// AUTO-GENERATED by bloom_cli (tailwindcss) — runs the in-browser
// Tailwind JIT engine, which scans the DOM for utility classes and
// injects a <style> tag. Do not edit by hand; regenerated by
// `bloom add`/`bloom remove`.
import '@tailwindcss/browser';
</script>
</head>
<body class="bg-[#111116] min-h-screen">
  <div id="app"></div>
</body>
</html>''';

      final sourceIndexHtml = File(p.join(tempDir.path, 'web', 'index.html'));
      sourceIndexHtml.writeAsStringSync(originalHtmlContent);

      final project = BloomProject.fromDirectory(tempDir);
      final builder = TailwindStaticBuild(project: project);

      final exitCode = await builder.build();
      expect(exitCode, 0);

      // Verify static output CSS exists and is non-empty
      final distCss = File(p.join(tempDir.path, 'web', 'dist', 'app.css'));
      expect(distCss.existsSync(), isTrue);
      expect(distCss.lengthSync(), greaterThan(0));

      final cssContent = distCss.readAsStringSync();
      expect(cssContent, contains('bg-indigo-600'));

      // Verify the PROJECT'S OWN source-of-truth index.html is completely UNCHANGED
      expect(sourceIndexHtml.readAsStringSync(), equals(originalHtmlContent));

      // Verify transformIndexHtml produces production copy with link tag replacing script tag
      final prodHtml = TailwindStaticBuild.transformIndexHtml(originalHtmlContent);
      expect(prodHtml, isNot(contains('@tailwindcss/browser')));
      expect(prodHtml, contains('<link rel="stylesheet" href="dist/app.css">'));
      expect(prodHtml, contains('<title>Tailwind Test</title>'));
    });

    test('transformIndexHtml rewrites both auto-generated and bare import script tags', () {
      const autoGeneratedHtml = '''<head>
  <title>App</title>
  <script type="module">
// AUTO-GENERATED by bloom_cli (tailwindcss) — runs the in-browser
// Tailwind JIT engine, which scans the DOM for utility classes and
// injects a <style> tag. Do not edit by hand; regenerated by
// `bloom add`/`bloom remove`.
import '@tailwindcss/browser';
</script>
</head>''';

      final result1 = TailwindStaticBuild.transformIndexHtml(autoGeneratedHtml);
      expect(result1, contains('<link rel="stylesheet" href="dist/app.css">'));
      expect(result1, isNot(contains('@tailwindcss/browser')));

      const bareImportHtml = '''<head>
  <title>App</title>
  <script type="module">
    import "@tailwindcss/browser";
  </script>
</head>''';

      final result2 = TailwindStaticBuild.transformIndexHtml(bareImportHtml);
      expect(result2, contains('<link rel="stylesheet" href="dist/app.css">'));
      expect(result2, isNot(contains('@tailwindcss/browser')));
    });

    test('BuildCommand executes Tailwind static build on web_dom target', () async {
      final bloomYaml = File(p.join(tempDir.path, 'bloom.yaml'));
      bloomYaml.writeAsStringSync('''
name: ecommerce_fixture_test
target: web_dom
npm_packages:
  "@tailwindcss/browser":
    version: 4.3.3
''');

      final sourceIndexHtml = File(p.join(tempDir.path, 'web', 'index.html'));
      sourceIndexHtml.writeAsStringSync('<html><head></head><body></body></html>');

      bool dartCompileCalled = false;
      final runner = CommandRunner<int>('bloom', 'Bloom CLI')
        ..addCommand(BuildCommand(
          processRunner: (exec, args, {workingDirectory, environment, includeParentEnvironment = true, runInShell = false, mode = ProcessStartMode.normal}) async {
            if (exec == 'dart' && args.contains('compile')) {
              dartCompileCalled = true;
              return ProcessResult(100, 0, 'Compiled', '');
            }
            return Process.run(
              exec,
              args,
              workingDirectory: workingDirectory,
              environment: environment,
              includeParentEnvironment: includeParentEnvironment,
              runInShell: runInShell,
            );
          },
        ));

      final exitCode = await runner.run([
        'build',
        'web_dom',
        '--project-dir',
        tempDir.path,
      ]);

      expect(exitCode, 0);
      expect(dartCompileCalled, isTrue);

      final distCss = File(p.join(tempDir.path, 'web', 'dist', 'app.css'));
      expect(distCss.existsSync(), isTrue);
    });
  });
}
