import 'package:bloom_js_native/bloom_js_native.dart';
import '../huge_icons.dart';

final activePipelineStep = signal(1);

BloomNode orchestrationPipeline() {
  final steps = const [
    (
      1,
      'STEP 01',
      'STANDARDIZE',
      'Standardize Architecture',
      'Establish unified directory conventions, configuration files, and project layout across all Flutter applications.',
      [
        'Next.js-inspired `lib/app/routes` directory hierarchy',
        'Unified `bloom.yaml` central environment manifest',
        'Deterministic boot sequence before `runApp()`',
      ],
      '// lib/app/routes/_layout.dart\nclass RootLayout extends BloomLayout {\n  @override\n  Widget build(BuildContext context, Widget child) {\n    return MainScaffold(body: child);\n  }\n}',
      'CONVENTIONS_ENGINE',
    ),
    (
      2,
      'STEP 02',
      'WRAP',
      'Thin Infrastructure Wrappers',
      'Wrap battle-tested Flutter packages (go_router, signals, dio) in zero-boilerplate, type-safe API abstractions.',
      [
        'Zero `setState` signals reactivity wrappers',
        'Type-safe route parameter extraction',
        'Scoped dependency injection container',
      ],
      '// Thin reactive state controller\nclass UserController extends BloomController {\n  final user = signal<User?>(null);\n  late final isLoggedIn = computed(() => user.value != null);\n}',
      'ZERO_BOILERPLATE',
    ),
    (
      3,
      'STEP 03',
      'GENERATE',
      'Deterministic Code Generation',
      'Eliminate manual route declaration and boilerplate via real-time AST parsing and instant background code generation.',
      [
        'Sub-50ms incremental route table compilation',
        'Auto-generated strongly typed navigation helpers',
        'Zero runtime reflection overhead (AOT safe)',
      ],
      '// Auto-generated by Bloom CLI\nclass AppRoutes {\n  static const userProfile = \'/users/:id\';\n  static void goToProfile(BuildContext ctx, {required String id}) =>\n    ctx.go(userProfile, params: {\'id\': id});\n}',
      'AST_COMPILER',
    ),
    (
      4,
      'STEP 04',
      'ORCHESTRATE',
      'Unified DX & CLI Tooling',
      'Single unified CLI orchestrating Dart pub, Flutter build tools, device pairing, and Shorebird OTA releases.',
      [
        'Wireless dev pairing with physical mobile devices',
        'Expo-style CLI diagnostic dashboard',
        'Atomic production build artifacts',
      ],
      r'$ bloom dev --device physical-ios'
          '\n'
          r'[+] Paired via Wi-Fi (192.168.1.42:5555)'
          '\n'
          r'[+] Hot reload listening at port 4321'
          '\n'
          r'[+] Impeller 60fps rendering active',
      'CLI_ORCHESTRATOR',
    ),
    (
      5,
      'STEP 05',
      'REPLACE GAPS',
      'Native Ecosystem Extensions',
      'Fill critical gaps in the Flutter ecosystem with custom-engineered primitives: Bloom Query, Bloom UI Studio, and Dev Client.',
      [
        'Declarative server-state caching & optimistic mutations',
        'shadcn-inspired mobile UI token components',
        'Shorebird cryptographic byte-patching pipeline',
      ],
      '// Declarative Bloom Query\nfinal userQuery = useBloomQuery(\n  key: \'user_profile\',\n  fetcher: () => api.getProfile(),\n  staleTime: Duration(minutes: 5),\n);',
      'ECOSYSTEM_GAP_FILL',
    ),
  ];

  return Div(
    className: 'max-w-5xl mx-auto space-y-8',
    children: [
      // Pipeline Step Nodes
      Div(
        className: 'grid grid-cols-2 sm:grid-cols-5 gap-3',
        children: [
          for (final (id, num, title, _, _, _, _, _) in steps)
            Live(() {
              final isActive = activePipelineStep.value == id;
              return Button(
                onClick: (_) => activePipelineStep.value = id,
                className:
                    'p-3.5 rounded-2xl text-left transition-all border ${isActive ? 'bg-purple-600 text-white border-purple-500 shadow-lg scale-[1.02] font-bold' : 'bg-slate-900/60 text-slate-400 border-zinc-800 hover:border-zinc-700 hover:text-white'}',
                children: [
                  Span(
                    className: 'text-[10px] font-mono block opacity-80 mb-0.5',
                    text: num,
                  ),
                  Span(
                    className: 'text-xs font-black block truncate',
                    text: title,
                  ),
                ],
              );
            }),
        ],
      ),

      // Active Step Content Display
      Live(() {
        final active = steps.firstWhere(
          (s) => s.$1 == activePipelineStep.value,
          orElse: () => steps.first,
        );

        return Div(
          className:
              'p-8 rounded-3xl bg-black border border-zinc-800 '
              'shadow-2xl grid grid-cols-1 lg:grid-cols-2 gap-8 '
              'items-center',
          children: [
            Div(
              className: 'space-y-4',
              children: [
                Span(
                  className:
                      'px-3 py-1 rounded-full bg-purple-500/10 text-purple-400 '
                      'text-xs font-mono font-bold border border-purple-500/20 '
                      'inline-block',
                  text: active.$8,
                ),
                H3(
                  className: 'text-2xl font-black text-white tracking-tight',
                  text: active.$4,
                ),
                P(
                  className: 'text-sm text-slate-400 leading-relaxed',
                  text: active.$5,
                ),
                Div(
                  className: 'space-y-2 pt-2',
                  children: [
                    for (final detail in active.$6)
                      Div(
                        className:
                            'flex items-center gap-2.5 text-xs text-slate-300',
                        children: [
                          hugeIcon(
                            'check',
                            className: 'w-4 h-4 text-emerald-400 shrink-0',
                          ),
                          Span(text: detail),
                        ],
                      ),
                  ],
                ),
              ],
            ),

            // Code Preview
            Div(
              className:
                  'rounded-2xl bg-zinc-950 p-5 border border-zinc-800 '
                  'font-mono text-xs text-slate-200 overflow-x-auto '
                  'leading-relaxed shadow-inner',
              children: [
                Pre(
                  className: 'm-0',
                  children: [Code(text: active.$7)],
                ),
              ],
            ),
          ],
        );
      }),
    ],
  );
}
