import 'dart:io';
import 'package:path/path.dart' as p;
import '../utils/ansi.dart';
import '../utils/project.dart';

/// Shorebird project deployment configuration.
class ShorebirdConfig {
  final String appId;
  final bool autoUpdate;
  final Map<String, String> flavors;

  const ShorebirdConfig({
    required this.appId,
    this.autoUpdate = true,
    this.flavors = const {},
  });

  /// Parse from dynamic YAML map.
  factory ShorebirdConfig.fromMap(Map<dynamic, dynamic> map) {
    final appId = map['app_id']?.toString() ?? map['appId']?.toString() ?? 'auto';
    final autoUpdate = map['auto_update'] as bool? ?? map['autoUpdate'] as bool? ?? true;
    final flavorsMap = <String, String>{};

    if (map['flavors'] is Map) {
      (map['flavors'] as Map).forEach((k, v) {
        flavorsMap[k.toString()] = v.toString();
      });
    }

    return ShorebirdConfig(
      appId: appId,
      autoUpdate: autoUpdate,
      flavors: flavorsMap,
    );
  }

  /// Generate shorebird.yaml content string.
  String toYamlContent({String? activeFlavor}) {
    final effectiveAppId = (activeFlavor != null && flavors.containsKey(activeFlavor))
        ? flavors[activeFlavor]!
        : appId;

    final buffer = StringBuffer();
    buffer.writeln('# Shorebird Configuration generated by Bloom CLI.');
    buffer.writeln('# https://docs.shorebird.dev');
    buffer.writeln('app_id: $effectiveAppId');
    buffer.writeln('auto_update: $autoUpdate');

    if (flavors.isNotEmpty) {
      buffer.writeln('flavors:');
      flavors.forEach((fl, id) {
        buffer.writeln('  $fl: $id');
      });
    }

    return buffer.toString();
  }
}

/// Synchronizes project configuration with shorebird.yaml.
class ShorebirdSynchronizer {
  final BloomProject project;

  ShorebirdSynchronizer(this.project);

  /// Ensure `shorebird.yaml` is present and synchronized with `bloom.yaml`.
  File sync({String? activeFlavor, String? overrideAppId}) {
    final bloomConfig = project.loadBloomConfig();
    final deploymentMap = bloomConfig['deployment'];

    ShorebirdConfig config;
    if (deploymentMap is Map && deploymentMap['shorebird'] is Map) {
      config = ShorebirdConfig.fromMap(deploymentMap['shorebird'] as Map);
    } else {
      config = ShorebirdConfig(
        appId: overrideAppId ?? 'bloom_${project.projectName}_app',
        autoUpdate: true,
      );
    }

    if (overrideAppId != null) {
      config = ShorebirdConfig(
        appId: overrideAppId,
        autoUpdate: config.autoUpdate,
        flavors: config.flavors,
      );
    }

    final shorebirdYamlFile = File(p.join(project.rootDir.path, 'shorebird.yaml'));
    final yamlString = config.toYamlContent(activeFlavor: activeFlavor);
    shorebirdYamlFile.writeAsStringSync(yamlString);
    print(Ansi.step('Synchronized shorebird.yaml (App ID: ${config.appId})'));

    return shorebirdYamlFile;
  }
}
