builders:
  bloom_model_builder:
    import: "package:bloom_db_generator/builder.dart"
    builder_factories: ["bloomModelBuilder"]
    build_extensions: { ".dart": [".bloom_model.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
