// lib/src/ui/font_link.dart
import '../framework.dart';

/// Returns a `<link rel="stylesheet" href="...">` [BloomNode] referencing
/// the self-hosted font stylesheet generated by `bloom fonts optimize`.
///
/// By default points to `/generated/fonts/fonts.g.css`.
///
/// Example:
/// ```dart
/// head.wrapDocument(bodyHtml, extraHead: renderToHtml(fontStylesheetLink()));
/// ```
BloomNode fontStylesheetLink({String href = '/generated/fonts/fonts.g.css'}) {
  return El(
    'link',
    attrs: {
      'rel': 'stylesheet',
      'href': href,
    },
  );
}
