// lib/src/web/ssr_engine.dart
import 'dart:io';
import 'package:path/path.dart' as p;
import '../utils/ansi.dart';
import '../utils/project.dart';

class DiscoveredApiRoute {
  final String path;
  final String relativeFilePath;
  final bool hasGet;
  final bool hasPost;
  final bool hasPut;
  final bool hasDelete;
  final bool hasPatch;

  DiscoveredApiRoute({
    required this.path,
    required this.relativeFilePath,
    this.hasGet = true,
    this.hasPost = false,
    this.hasPut = false,
    this.hasDelete = false,
    this.hasPatch = false,
  });
}

/// Server-Side Rendering (SSR) & API Router Bundle Engine for Bloom.
///
/// Emits executable Dart server (`build/server.dart`) handling API endpoints and dynamic SSR HTML.
class BloomSsrEngine {
  final BloomProject project;
  final Directory outputDir;

  BloomSsrEngine({
    required this.project,
    Directory? outputDir,
  }) : outputDir = outputDir ?? Directory(p.join(project.rootDir.path, 'build'));

  /// Discovers all API routes in `lib/routes/api/`.
  List<DiscoveredApiRoute> discoverApiRoutes() {
    final apiDir = Directory(p.join(project.rootDir.path, 'lib', 'routes', 'api'));
    if (!apiDir.existsSync()) return [];

    final routes = <DiscoveredApiRoute>[];
    final files = apiDir.listSync(recursive: true).whereType<File>();

    for (final file in files) {
      if (!file.path.endsWith('.dart')) continue;
      final relPath = p.relative(file.path, from: apiDir.path);
      if (p.basename(relPath).startsWith('_')) continue; // Skip middleware files

      var routePath = relPath.replaceAll('.dart', '');
      if (routePath == 'index' || routePath.endsWith('/index')) {
        routePath = routePath.replaceAll(RegExp(r'/?index$'), '');
      }

      // Convert [param] to :param for router matching
      routePath = routePath.replaceAllMapped(RegExp(r'\[(.*?)\]'), (m) => ':${m.group(1)}');
      if (!routePath.startsWith('/')) {
        routePath = '/$routePath';
      }

      final fullApiPath = '/api$routePath';

      final content = file.readAsStringSync();
      routes.add(DiscoveredApiRoute(
        path: fullApiPath,
        relativeFilePath: relPath,
        hasGet: content.contains('get(BloomRequest') || content.contains('get(request') || content.contains('Future<BloomResponse> get('),
        hasPost: content.contains('post(BloomRequest') || content.contains('post(request') || content.contains('Future<BloomResponse> post('),
        hasPut: content.contains('put(BloomRequest') || content.contains('put(request') || content.contains('Future<BloomResponse> put('),
        hasDelete: content.contains('delete(BloomRequest') || content.contains('delete(request') || content.contains('Future<BloomResponse> delete('),
        hasPatch: content.contains('patch(BloomRequest') || content.contains('patch(request') || content.contains('Future<BloomResponse> patch('),
      ));
    }

    routes.sort((a, b) => a.path.compareTo(b.path));
    return routes;
  }

  /// Generates the standalone SSR and API server file (`build/server.dart`).
  Future<File> generate() async {
    print(Ansi.boldText('\n🖥️  Building Bloom Full-Stack SSR & API Server...'));

    if (!outputDir.existsSync()) {
      outputDir.createSync(recursive: true);
    }

    final apiRoutes = discoverApiRoutes();
    print('› Discovered ${apiRoutes.length} backend API endpoint(s).');

    final serverFile = File(p.join(outputDir.path, 'server.dart'));
    final code = _generateServerDartCode(apiRoutes);
    serverFile.writeAsStringSync(code);

    print(Ansi.success('✔ Server bundle generated: ${serverFile.path}\n'));
    return serverFile;
  }

  String _generateServerDartCode(List<DiscoveredApiRoute> apiRoutes) {
    final buffer = StringBuffer();
    buffer.writeln('// AUTO-GENERATED BY BLOOM CLI. DO NOT EDIT.');
    buffer.writeln('// Standalone Server-Side Rendering (SSR) & API Route Runtime Server.');
    buffer.writeln();
    buffer.writeln("import 'dart:io';");
    buffer.writeln("import 'dart:typed_data';");
    buffer.writeln("import 'package:bloom_framework/bloom_server.dart';");
    buffer.writeln();

    // Import API route files
    for (var i = 0; i < apiRoutes.length; i++) {
      final r = apiRoutes[i];
      final importPath = '../lib/routes/api/${r.relativeFilePath.replaceAll(r'\', '/')}';
      buffer.writeln("import '$importPath' as api_route_$i;");
    }
    buffer.writeln();

    buffer.writeln('Future<void> main(List<String> args) async {');
    buffer.writeln("  final port = int.tryParse(Platform.environment['PORT'] ?? '8080') ?? 8080;");
    buffer.writeln('  final router = BloomApiRouter();');
    buffer.writeln('  router.use(BloomCorsMiddleware());');
    buffer.writeln();

    // Register API endpoints
    buffer.writeln('  // Registered API Routes');
    for (var i = 0; i < apiRoutes.length; i++) {
      final r = apiRoutes[i];
      if (r.hasGet) {
        buffer.writeln("  router.get('${r.path}', (req) => api_route_$i.get(req));");
      }
      if (r.hasPost) {
        buffer.writeln("  router.post('${r.path}', (req) => api_route_$i.post(req));");
      }
      if (r.hasPut) {
        buffer.writeln("  router.put('${r.path}', (req) => api_route_$i.put(req));");
      }
      if (r.hasDelete) {
        buffer.writeln("  router.delete('${r.path}', (req) => api_route_$i.delete(req));");
      }
      if (r.hasPatch) {
        buffer.writeln("  router.patch('${r.path}', (req) => api_route_$i.patch(req));");
      }
    }
    buffer.writeln();

    // Catch-all SSR & Static File Handler
    buffer.writeln('''
  // Catch-all SSR HTML Fallback & Web Asset Handler
  router.all('*', (req) async {
    final webDir = Directory('build/web');
    if (webDir.existsSync()) {
      final staticFile = File('\${webDir.path}\${req.path}');
      if (staticFile.existsSync() && !FileSystemEntity.isDirectorySync(staticFile.path)) {
        final bytes = staticFile.readAsBytesSync();
        final ext = staticFile.path.split('.').last.toLowerCase();
        final contentType = _getContentType(ext);
        return BloomResponse(
          statusCode: 200,
          headers: {'content-type': contentType},
          body: Uint8List.fromList(bytes),
        );
      }

      final indexFile = File('\${webDir.path}/index.html');
      if (indexFile.existsSync()) {
        final html = indexFile.readAsStringSync();
        return BloomResponse.html(html);
      }
    }

    return BloomResponse.html('<h1>Bloom SSR Server</h1><p>Running on port ' + port.toString() + '</p>');
  });

  final server = await router.serve(port: port);
  print('🚀 Bloom Full-Stack Server listening on http://localhost:\$port');
}

String _getContentType(String extension) {
  switch (extension) {
    case 'html': return 'text/html; charset=utf-8';
    case 'js': return 'application/javascript; charset=utf-8';
    case 'css': return 'text/css; charset=utf-8';
    case 'json': return 'application/json; charset=utf-8';
    case 'png': return 'image/png';
    case 'jpg':
    case 'jpeg': return 'image/jpeg';
    case 'svg': return 'image/svg+xml';
    default: return 'application/octet-stream';
  }
}
''');

    return buffer.toString();
  }
}
