// lib/src/web/tailwind_static_build.dart
import 'dart:io';
import 'package:path/path.dart' as p;
import '../npm/npm_manifest.dart';
import '../utils/ansi.dart';
import '../utils/project.dart';

/// Default process runner function.
Future<ProcessResult> _defaultProcessRunner(
  String executable,
  List<String> arguments, {
  String? workingDirectory,
  Map<String, String>? environment,
  bool includeParentEnvironment = true,
  bool runInShell = false,
  ProcessStartMode mode = ProcessStartMode.normal,
}) {
  return Process.run(
    executable,
    arguments,
    workingDirectory: workingDirectory,
    environment: environment,
    includeParentEnvironment: includeParentEnvironment,
    runInShell: runInShell,
  );
}

/// Default Bun runtime availability check.
bool _defaultHasBunCheck() {
  try {
    final res = Process.runSync('bun', ['--version']);
    return res.exitCode == 0;
  } catch (_) {
    return false;
  }
}

/// Manages production static CSS generation with Tailwind CSS v4 CLI (`@tailwindcss/cli`).
///
/// Pre-scans project source files (`.dart`) and emits an optimized, minified static
/// stylesheet (`web/dist/app.css`) for production builds, removing the need for runtime
/// DOM scanning with `@tailwindcss/browser`.
class TailwindStaticBuild {
  final BloomProject project;
  final Future<ProcessResult> Function(
    String executable,
    List<String> arguments, {
    String? workingDirectory,
    Map<String, String>? environment,
    bool includeParentEnvironment,
    bool runInShell,
    ProcessStartMode mode,
  }) processRunner;
  final bool Function() hasBunCheck;

  /// Regular expression matching the dev-mode Tailwind script tag in `index.html`.
  ///
  /// Matches both auto-generated blocks from `ImportMapManager` and inline module import tags.
  static final RegExp tailwindScriptRegex = RegExp(
    r'<script\s+type=["\x27]module["\x27]>(?:\s*\/\/\s*AUTO-GENERATED by bloom_cli \(tailwindcss\)[\s\S]*?|\s*import\s+["\x27]@tailwindcss\/browser["\x27];?\s*)<\/script>',
    caseSensitive: false,
  );

  TailwindStaticBuild({
    required this.project,
    this.processRunner = _defaultProcessRunner,
    this.hasBunCheck = _defaultHasBunCheck,
  });

  /// Checks if the project declares `@tailwindcss/browser` in `bloom.yaml`.
  bool get isTailwindProject {
    final manifest = NpmManifest.read(project);
    return manifest.packages.any((e) =>
        e.npmName == '@tailwindcss/browser' ||
        e.alias == '@tailwindcss/browser');
  }

  /// Transforms [html] by replacing the dev-mode Tailwind script tag with a static `<link>` stylesheet tag.
  static String transformIndexHtml(
    String html, {
    String cssHref = 'dist/app.css',
  }) {
    final linkTag = '<link rel="stylesheet" href="$cssHref">';
    if (tailwindScriptRegex.hasMatch(html)) {
      return html.replaceFirst(tailwindScriptRegex, linkTag);
    }
    if (html.contains(linkTag)) {
      return html;
    }
    if (html.contains('</head>')) {
      return html.replaceFirst('</head>', '  $linkTag\n</head>');
    }
    return '$linkTag\n$html';
  }

  /// Executes the static Tailwind CSS build step.
  ///
  /// Returns exit code (0 on success or no-op, non-zero on failure).
  Future<int> build({
    File? customInputFile,
    File? customOutputFile,
  }) async {
    if (!isTailwindProject) {
      return 0;
    }

    if (!hasBunCheck()) {
      print(Ansi.error(
        '✖ Tailwind CSS build failed: Bun is required to run the Tailwind static build toolchain.\n'
        'Please install Bun (https://bun.sh) and ensure it is available on your PATH.',
      ));
      return 1;
    }

    // 1. Determine input entry CSS file
    final File inputFile;
    if (customInputFile != null) {
      inputFile = customInputFile;
    } else {
      final userEntry = File(p.join(project.rootDir.path, 'web', 'tailwind.css'));
      if (userEntry.existsSync()) {
        inputFile = userEntry;
      } else {
        final generatedDir = Directory(p.join(project.rootDir.path, '.dart_tool', 'bloom'));
        if (!generatedDir.existsSync()) {
          generatedDir.createSync(recursive: true);
        }
        final autoEntry = File(p.join(generatedDir.path, 'tailwind_entry.css'));
        autoEntry.writeAsStringSync('@import "tailwindcss";\n');
        inputFile = autoEntry;
      }
    }

    // 2. Determine output CSS destination
    final outputFile = customOutputFile ??
        File(p.join(project.rootDir.path, 'web', 'dist', 'app.css'));
    if (!outputFile.parent.existsSync()) {
      outputFile.parent.createSync(recursive: true);
    }

    // 3. Ensure Tailwind CLI & package are available in toolchain directory
    final toolDir = Directory(p.join(project.rootDir.path, '.dart_tool', 'bloom'));
    final toolNodeModules = Directory(p.join(toolDir.path, 'node_modules'));
    final tailwindPackage = Directory(p.join(toolNodeModules.path, 'tailwindcss'));

    if (!tailwindPackage.existsSync()) {
      if (!toolDir.existsSync()) {
        toolDir.createSync(recursive: true);
      }
      final installResult = await processRunner(
        'bun',
        ['add', '@tailwindcss/cli', 'tailwindcss'],
        workingDirectory: toolDir.path,
      );
      if (installResult.exitCode != 0) {
        print(Ansi.error('Failed to install @tailwindcss/cli toolchain:\n${installResult.stdout}\n${installResult.stderr}'));
        return installResult.exitCode == 0 ? 1 : installResult.exitCode;
      }
    }

    // 4. Execute bunx @tailwindcss/cli with NODE_PATH pointing to toolchain node_modules
    final env = Map<String, String>.from(Platform.environment);
    final nodePaths = [
      if (toolNodeModules.existsSync()) toolNodeModules.path,
      if (env['NODE_PATH'] != null && env['NODE_PATH']!.isNotEmpty) env['NODE_PATH']!,
    ].join(':');
    if (nodePaths.isNotEmpty) {
      env['NODE_PATH'] = nodePaths;
    }

    print(Ansi.step('Building static Tailwind CSS bundle (bunx @tailwindcss/cli)...'));
    final result = await processRunner(
      'bunx',
      [
        '@tailwindcss/cli',
        '-i',
        p.relative(inputFile.path, from: project.rootDir.path),
        '-o',
        p.relative(outputFile.path, from: project.rootDir.path),
        '--minify',
      ],
      workingDirectory: project.rootDir.path,
      environment: env,
    );

    if (result.exitCode != 0) {
      print(Ansi.error('Tailwind CLI build failed:\n${result.stdout}\n${result.stderr}'));
      return result.exitCode == 0 ? 1 : result.exitCode;
    }

    if (outputFile.existsSync()) {
      final sizeKb = (outputFile.lengthSync() / 1024).toStringAsFixed(1);
      final relPath = p.relative(outputFile.path, from: project.rootDir.path);
      print(Ansi.success('✓ Generated static Tailwind CSS: $relPath (${sizeKb}kB)'));
    }

    return 0;
  }
}
