// lib/src/assets/asset_generator.dart
import 'dart:io';
import 'package:path/path.dart' as p;
import '../utils/ansi.dart';
import '../utils/project.dart';

/// Generates strongly-typed asset accessor constants (`lib/generated/assets.g.dart`).
class AssetGenerator {
  /// The target Bloom project.
  final BloomProject project;

  /// Directory containing assets to generate references for (defaults to `assets/`).
  final Directory assetsDir;

  /// Target output file for generated Dart code (defaults to `lib/generated/assets.g.dart`).
  final File outputFile;

  /// Creates an asset code generator for [project].
  ///
  /// Optionally overrides the source [assetsDir] and destination [outputFile].
  AssetGenerator({
    required this.project,
    Directory? assetsDir,
    File? outputFile,
  })  : assetsDir = assetsDir ?? Directory(p.join(project.rootDir.path, 'assets')),
        outputFile = outputFile ??
            File(p.join(project.rootDir.path, 'lib', 'generated', 'assets.g.dart'));

  /// Generates the strongly typed Dart file and returns the written [File].
  File generate() {
    print(Ansi.boldText('\n⚡ Generating Typed Asset References...'));

    if (!outputFile.parent.existsSync()) {
      outputFile.parent.createSync(recursive: true);
    }

    final physicalAssets = assetsDir.existsSync()
        ? (assetsDir.listSync(recursive: true).whereType<File>().toList()
          ..sort((a, b) => a.path.compareTo(b.path)))
        : <File>[];

    // Group assets by category (top-level subfolder under assets/)
    final categoryMap = <String, Map<String, String>>{};

    for (final asset in physicalAssets) {
      final relFromAssets = p.relative(asset.path, from: assetsDir.path).replaceAll('\\', '/');
      final parts = relFromAssets.split('/');
      final categoryName = parts.length > 1 ? parts[0] : 'misc';
      final fileName = parts.last;
      final varName = _toCamelCase(p.withoutExtension(fileName));

      final projectRelPath = p.relative(asset.path, from: project.rootDir.path).replaceAll('\\', '/');

      categoryMap.putIfAbsent(categoryName, () => <String, String>{})[varName] = projectRelPath;
    }

    final buffer = StringBuffer();
    buffer.writeln('// AUTO-GENERATED BY BLOOM CLI. DO NOT EDIT.');
    buffer.writeln('// Cryptographically verified, type-safe asset identifiers for Bloom.');
    buffer.writeln('// ignore_for_file: constant_identifier_names, non_constant_identifier_names, unused_element, unused_field');
    buffer.writeln();

    // Top-level class Assets
    buffer.writeln('abstract class Assets {');
    buffer.writeln('  Assets._();');
    for (final cat in categoryMap.keys.toList()..sort()) {
      final catClassName = '_Assets${_toPascalCase(cat)}';
      final catField = _toCamelCase(cat);
      buffer.writeln('  static const $catField = $catClassName();');
    }
    buffer.writeln('}');
    buffer.writeln();

    // Category classes
    for (final cat in categoryMap.keys.toList()..sort()) {
      final catClassName = '_Assets${_toPascalCase(cat)}';
      buffer.writeln('class $catClassName {');
      buffer.writeln('  const $catClassName();');
      final entries = categoryMap[cat]!;
      final sortedKeys = entries.keys.toList()..sort();
      for (final key in sortedKeys) {
        final assetPath = entries[key]!;
        buffer.writeln("  final String $key = '$assetPath';");
      }
      buffer.writeln('}');
      buffer.writeln();
    }

    outputFile.writeAsStringSync(buffer.toString());
    print(Ansi.success('✔ Generated typed asset references: ${outputFile.path} (${physicalAssets.length} assets mapped)\n'));

    return outputFile;
  }

  String _toCamelCase(String text) {
    var cleaned = text.replaceAll(RegExp(r'[^a-zA-Z0-9_]'), '_');
    if (RegExp(r'^[0-9]').hasMatch(cleaned)) {
      cleaned = 'asset_$cleaned';
    }
    final parts = cleaned.split('_').where((s) => s.isNotEmpty).toList();
    if (parts.isEmpty) return 'asset';
    return parts.first.toLowerCase() +
        parts.skip(1).map((p) => p.substring(0, 1).toUpperCase() + p.substring(1).toLowerCase()).join('');
  }

  String _toPascalCase(String text) {
    final camel = _toCamelCase(text);
    if (camel.isEmpty) return 'Category';
    return camel.substring(0, 1).toUpperCase() + camel.substring(1);
  }
}
