import 'dart:io';
import 'package:http/http.dart' as http;

class DtsCodegen {
  final http.Client _client;
  DtsCodegen({http.Client? httpClient}) : _client = httpClient ?? http.Client();

  /// Fetches TypeScript definitions (.d.ts) from esm.sh or DefinitelyTyped and
  /// generates a Dart 3.5+ @JS() extension type binding file.
  ///
  /// [jsGlobalHint] — the JS global name from [NpmPackageDescriptor.jsGlobal],
  /// so we never have to hardcode per-package global names in this class.
  Future<void> generate({
    required String packageName,
    required String version,
    required String outputPath,
    String? jsGlobalHint,
  }) async {
    final String esmUrl = 'https://esm.sh/$packageName@$version';
    String? dtsContent;

    try {
      // 1. Ask esm.sh for the TypeScript types header
      final resp = await _client.get(Uri.parse(esmUrl));
      final dtsUrl = resp.headers['x-typescript-types'];

      if (dtsUrl != null) {
        final dtsResp = await _client.get(Uri.parse(dtsUrl));
        if (dtsResp.statusCode == 200) dtsContent = dtsResp.body;
      }

      // 2. Fall back to DefinitelyTyped (@types/*)
      if (dtsContent == null || dtsContent.isEmpty) {
        final atPkg = packageName.startsWith('@')
            ? packageName.replaceAll('@', '').replaceAll('/', '__')
            : packageName;
        final dtUrl = 'https://esm.sh/@types/$atPkg/index.d.ts';
        final dtResp = await _client.get(Uri.parse(dtUrl));
        if (dtResp.statusCode == 200) dtsContent = dtResp.body;
      }
    } catch (_) {
      // Network failure — still emit a usable fallback binding
    }

    final dartCode = _emit(packageName, version, dtsContent, jsGlobalHint);
    final outFile = File(outputPath);
    await outFile.parent.create(recursive: true);
    await outFile.writeAsString(dartCode);
  }

  String _emit(
    String packageName,
    String version,
    String? dts,
    String? jsGlobalHint,
  ) {
    final className = _toPascalCase(packageName);
    // jsGlobalHint from the catalog takes priority; only fall back to heuristic
    final jsGlobal = jsGlobalHint ?? _inferGlobal(packageName);

    final globalAnnotation = '@JS(\'$jsGlobal\')';
    // A well-formed JS identifier can be bound directly as a top-level
    // external function name; anything else (scoped-package-derived globals
    // rarely produce this, but stay defensive) falls back to a wrapper name
    // so the generated file always compiles.
    final callableName =
        RegExp(r'^[A-Za-z_$][A-Za-z0-9_$]*$').hasMatch(jsGlobal)
            ? jsGlobal
            : '${_toCamelCase(className)}Call';

    return '''// AUTO-GENERATED by `bloom add $packageName`
// NPM package  : $packageName@$version
// JS global    : $jsGlobal
// DO NOT EDIT  — run `bloom add $packageName` to regenerate.
//
// ignore_for_file: non_constant_identifier_names, avoid_js_interop_library_on_non_web_platforms, unused_import

import 'dart:js_interop';
import 'package:web/web.dart' as web;

/// Dart 3.5+ JS Interop binding for the `$packageName` NPM package.
///
/// This file was auto-generated from the package\'s TypeScript declarations
/// ${dts != null ? 'fetched from esm.sh / DefinitelyTyped.' : '(no .d.ts found — dynamic proxy emitted).'}
///
/// Many npm packages (clsx, class-variance-authority, tailwind-merge, and
/// most small utility libraries) export a *callable function* as their
/// default export, not an object with named methods — there is no method
/// name to hand [$className.callMethod], so that member alone cannot invoke
/// them. [$callableName] below binds the JS global directly as a callable
/// Dart top-level function for exactly that case; pass only the leading
/// arguments you need, the rest default to omitted (`undefined` in JS).
///
/// Usage:
///   $callableName(arg0.jsify(), arg1.jsify())   // package exports a function
///   $jsGlobal.method(...)                       // package exports an object — via callMethod below
@JS('$jsGlobal')
external JSAny? $callableName([
  JSAny? a0,
  JSAny? a1,
  JSAny? a2,
  JSAny? a3,
  JSAny? a4,
  JSAny? a5,
]);

$globalAnnotation
extension type $className(JSObject _) implements JSObject {
  /// Call a named method on the JS object form of this package (only
  /// applicable if it exports an object rather than a bare function — see
  /// [$callableName] above for the function case).
  /// For better type safety, extend this file with explicit external members.
  external JSAny? callMethod(String method, [JSArray<JSAny?>? args]);
}
''';
  }

  String _toCamelCase(String pascal) =>
      pascal.isEmpty ? pascal : pascal[0].toLowerCase() + pascal.substring(1);

  String _toPascalCase(String input) {
    final clean = input.replaceAll('@', '').replaceAll('/', '_').replaceAll('-', '_');
    return clean
        .split('_')
        .where((s) => s.isNotEmpty)
        .map((s) => s[0].toUpperCase() + s.substring(1))
        .join();
  }

  /// Last-resort heuristic for packages not in the catalog.
  /// The catalog's [jsGlobalHint] is always preferred over this.
  String _inferGlobal(String pkg) {
    return pkg
        .replaceAll('@', '')
        .replaceAll('/', '_')
        .replaceAll('-', '_');
  }
}
