import 'dart:collection';
import 'dart:io';
import 'package:http/http.dart' as http;

class DtsCodegen {
  final http.Client _client;
  DtsCodegen({http.Client? httpClient}) : _client = httpClient ?? http.Client();

  /// Fetches TypeScript definitions (.d.ts) from esm.sh or DefinitelyTyped and
  /// generates a Dart 3.5+ @JS() extension type binding file.
  ///
  /// [jsGlobalHint] — the JS global name from [NpmPackageDescriptor.jsGlobal],
  /// so we never have to hardcode per-package global names in this class.
  Future<void> generate({
    required String packageName,
    required String version,
    required String outputPath,
    String? jsGlobalHint,
  }) async {
    final String esmUrl = 'https://esm.sh/$packageName@$version';
    String? dtsContent;

    try {
      // 1. Ask esm.sh for the TypeScript types header
      final resp = await _client.get(Uri.parse(esmUrl));
      final dtsUrl = resp.headers['x-typescript-types'];

      if (dtsUrl != null) {
        final dtsResp = await _client.get(Uri.parse(dtsUrl));
        if (dtsResp.statusCode == 200) dtsContent = dtsResp.body;
      }

      // 2. Fall back to DefinitelyTyped (@types/*)
      if (dtsContent == null || dtsContent.isEmpty) {
        final atPkg = packageName.startsWith('@')
            ? packageName.replaceAll('@', '').replaceAll('/', '__')
            : packageName;
        final dtUrl = 'https://esm.sh/@types/$atPkg/index.d.ts';
        final dtResp = await _client.get(Uri.parse(dtUrl));
        if (dtResp.statusCode == 200) dtsContent = dtResp.body;
      }
    } catch (_) {
      // Network failure — still emit a usable fallback binding
    }

    final dartCode = _emit(packageName, version, dtsContent, jsGlobalHint);
    final outFile = File(outputPath);
    await outFile.parent.create(recursive: true);
    await outFile.writeAsString(dartCode);
  }

  String _emit(
    String packageName,
    String version,
    String? dts,
    String? jsGlobalHint,
  ) {
    final className = _toPascalCase(packageName);
    // jsGlobalHint from the catalog takes priority; only fall back to heuristic
    final jsGlobal = jsGlobalHint ?? _inferGlobal(packageName);

    final getterName = _isValidDartIdentifier(jsGlobal)
        ? jsGlobal
        : '${_toCamelCase(className)}Global';

    final exports = dts != null ? parseExports(dts) : <String>{};

    final buffer = StringBuffer();
    buffer.writeln('// AUTO-GENERATED by `bloom add $packageName`');
    buffer.writeln('// NPM package  : $packageName@$version');
    buffer.writeln('// JS global    : $jsGlobal');
    buffer.writeln('// DO NOT EDIT  — run `bloom add $packageName` to regenerate.');
    buffer.writeln('//');
    buffer.writeln('// ignore_for_file: non_constant_identifier_names, avoid_js_interop_library_on_non_web_platforms, unused_import');
    buffer.writeln();
    buffer.writeln("import 'dart:js_interop';");
    buffer.writeln("import 'package:web/web.dart' as web;");
    buffer.writeln();
    buffer.writeln('/// Dart 3.5+ JS Interop binding for the `$packageName` NPM package.');
    buffer.writeln('///');
    buffer.writeln('/// This file was auto-generated from the package\'s TypeScript declarations');
    buffer.writeln('/// ${dts != null ? 'fetched from esm.sh / DefinitelyTyped.' : '(no .d.ts found — dynamic proxy emitted).'}');
    buffer.writeln('///');
    buffer.writeln('/// The package namespace is bridged onto `window.$jsGlobal` via the bootstrap');
    buffer.writeln('/// script in `web/index.html`. Access members through the top-level [$getterName] getter.');
    buffer.writeln('///');
    buffer.writeln('/// Usage:');
    buffer.writeln('///   $getterName.<member>(...)');
    buffer.writeln('@JS(\'$jsGlobal\')');
    buffer.writeln('external $className get $getterName;');
    buffer.writeln();
    buffer.writeln('@JS(\'$jsGlobal\')');
    buffer.writeln('extension type $className(JSObject _) implements JSObject {');

    if (exports.isNotEmpty) {
      for (final exp in exports) {
        final dartMemberName = _toDartMemberName(exp);
        buffer.writeln('  @JS(\'$exp\')');
        buffer.writeln('  external JSAny? $dartMemberName([');
        buffer.writeln('    JSAny? a0,');
        buffer.writeln('    JSAny? a1,');
        buffer.writeln('    JSAny? a2,');
        buffer.writeln('    JSAny? a3,');
        buffer.writeln('    JSAny? a4,');
        buffer.writeln('    JSAny? a5,');
        buffer.writeln('  ]);');
      }
    } else {
      // Fallback: no .d.ts found or no parseable exports.
      // Emitting a single best-effort member guess based on the package name.
      // Note: this member name is unverified and may not match the runtime export.
      final fallbackProp = _toCamelCase(className);
      final fallbackDartName = _toDartMemberName(fallbackProp);
      buffer.writeln('  /// Fallback member guess (no .d.ts found or no parseable exports).');
      buffer.writeln('  /// Note: this member name is unverified and may not match runtime exports.');
      buffer.writeln('  @JS(\'$fallbackProp\')');
      buffer.writeln('  external JSAny? $fallbackDartName([');
      buffer.writeln('    JSAny? a0,');
      buffer.writeln('    JSAny? a1,');
      buffer.writeln('    JSAny? a2,');
      buffer.writeln('    JSAny? a3,');
      buffer.writeln('    JSAny? a4,');
      buffer.writeln('    JSAny? a5,');
      buffer.writeln('  ]);');
    }

    buffer.writeln('  /// Call a named method on the JS object form of this package.');
    buffer.writeln('  /// Note: this member maps to a literal JS property named `callMethod` on the');
    buffer.writeln('  /// target object, not a dynamic-dispatch-by-name call. It only works if the');
    buffer.writeln('  /// target object happens to define a method literally named `callMethod`.');
    buffer.writeln('  external JSAny? callMethod(String method, [JSArray<JSAny?>? args]);');
    buffer.writeln('}');
    buffer.writeln();

    return buffer.toString();
  }

  /// Parses TypeScript definition (.d.ts) content for exported member names.
  static Set<String> parseExports(String dts) {
    final exports = LinkedHashSet<String>();

    // 1. export declare function / export function
    final funcRegex = RegExp(
      r'export\s+(?:declare\s+)?function\s+([A-Za-z_$][A-Za-z0-9_$]*)',
      multiLine: true,
    );
    for (final match in funcRegex.allMatches(dts)) {
      exports.add(match.group(1)!);
    }

    // 2. export declare const/let/var / export const/let/var
    final constRegex = RegExp(
      r'export\s+(?:declare\s+)?(?:const|let|var)\s+([A-Za-z_$][A-Za-z0-9_$]*)',
      multiLine: true,
    );
    for (final match in constRegex.allMatches(dts)) {
      exports.add(match.group(1)!);
    }

    // 3. export default <name> or export default function <name>
    final defaultRegex = RegExp(
      r'export\s+default\s+(?:function\s+)?([A-Za-z_$][A-Za-z0-9_$]*)?',
      multiLine: true,
    );
    for (final match in defaultRegex.allMatches(dts)) {
      final name = match.group(1);
      if (name != null && name.isNotEmpty && name != 'function') {
        exports.add(name);
      }
      exports.add('default');
    }

    // 4. Barrel re-exports: export { a, b as c, ... }
    // Avoid matching 'export type { ... }'
    final barrelRegex = RegExp(
      r'export\s*(?!type\b)\{\s*([^}]+)\s*\}',
      multiLine: true,
    );
    for (final match in barrelRegex.allMatches(dts)) {
      final block = match.group(1)!;
      final items = block.split(',');
      for (final item in items) {
        final clean = item.trim();
        if (clean.isEmpty) continue;
        if (clean.startsWith('type ')) {
          continue;
        }
        if (clean.contains(RegExp(r'\s+as\s+'))) {
          final parts = clean.split(RegExp(r'\s+as\s+'));
          if (parts.length == 2) {
            final alias = parts[1].trim();
            if (RegExp(r'^[A-Za-z_$][A-Za-z0-9_$]*$').hasMatch(alias)) {
              exports.add(alias);
            }
          }
        } else {
          if (RegExp(r'^[A-Za-z_$][A-Za-z0-9_$]*$').hasMatch(clean)) {
            exports.add(clean);
          }
        }
      }
    }

    return exports;
  }

  static const _reservedKeywords = {
    'assert', 'break', 'case', 'catch', 'class', 'const', 'continue', 'default',
    'do', 'else', 'enum', 'extends', 'false', 'final', 'finally', 'for', 'if',
    'in', 'is', 'new', 'null', 'rethrow', 'return', 'super', 'switch', 'this',
    'throw', 'true', 'try', 'var', 'void', 'while', 'with', 'async', 'hide',
    'of', 'on', 'show', 'sync', 'await', 'yield',
  };

  static bool _isValidDartIdentifier(String s) {
    if (!RegExp(r'^[A-Za-z_$][A-Za-z0-9_$]*$').hasMatch(s)) return false;
    return !_reservedKeywords.contains(s);
  }

  static String _toDartMemberName(String exp) {
    if (_reservedKeywords.contains(exp)) {
      return '${exp}_';
    }
    if (RegExp(r'^[A-Za-z_$][A-Za-z0-9_$]*$').hasMatch(exp)) {
      return exp;
    }
    return 'prop_${exp.replaceAll(RegExp(r'[^A-Za-z0-9_$]'), '_')}';
  }

  static String _toCamelCase(String pascal) =>
      pascal.isEmpty ? pascal : pascal[0].toLowerCase() + pascal.substring(1);

  static String _toPascalCase(String input) {
    final clean = input.replaceAll('@', '').replaceAll('/', '_').replaceAll('-', '_');
    return clean
        .split('_')
        .where((s) => s.isNotEmpty)
        .map((s) => s[0].toUpperCase() + s.substring(1))
        .join();
  }

  /// Last-resort heuristic for packages not in the catalog.
  /// The catalog's [jsGlobalHint] is always preferred over this.
  static String _inferGlobal(String pkg) {
    return pkg
        .replaceAll('@', '')
        .replaceAll('/', '_')
        .replaceAll('-', '_');
  }
}

