import 'dart:convert';
import 'dart:io';
import 'package:path/path.dart' as p;
import 'npm_manifest.dart';

class ImportMapManager {
  final String projectRoot;

  ImportMapManager(this.projectRoot);

  File get _indexHtml => File(p.join(projectRoot, 'web', 'index.html'));

  static final RegExp _importMapRegex = RegExp(
    r'<script\s+type=["\x27]importmap["\x27]>([\s\S]*?)<\/script>',
    caseSensitive: false,
  );

  // Negative lookahead excludes the tailwind script's comment below — both
  // start with "AUTO-GENERATED by bloom_cli" and this regex is otherwise
  // non-anchored/lazy, so without the exclusion it matches (and clobbers)
  // the tailwind script block whenever it appears first in the document.
  static final RegExp _bootstrapRegex = RegExp(
    r'<script\s+type=["\x27]module["\x27]>\s*\/\/\s*AUTO-GENERATED by bloom_cli(?! \(tailwindcss\))[\s\S]*?<\/script>',
    caseSensitive: false,
  );

  /// `@tailwindcss/browser` is a side-effect-only ESM module (it scans the
  /// DOM and injects a `<style>` tag on import; it has no meaningful JS API
  /// to bridge onto a `window` global), so it gets its own dedicated
  /// self-executing `<script type="module">` tag instead of going through
  /// the window-global bootstrap block that every other npm package uses.
  static const _tailwindBrowserPackage = '@tailwindcss/browser';

  static final RegExp _tailwindScriptRegex = RegExp(
    r'<script\s+type=["\x27]module["\x27]>\s*\/\/\s*AUTO-GENERATED by bloom_cli \(tailwindcss\)[\s\S]*?<\/script>',
    caseSensitive: false,
  );

  static String safeAlias(String pkg) =>
      pkg.replaceAll('@', '').replaceAll('/', '_').replaceAll('-', '_').replaceAll('.', '_');

  static String inferGlobal(String pkg) => safeAlias(pkg);

  /// Adds or updates an entry in the <script type="importmap"> block in web/index.html,
  /// and updates the bootstrap <script type="module"> block for ESM bridging.
  Future<void> addEntry({
    required String packageName,
    required String vendorPath,
    String? jsGlobal,
  }) async {
    final file = _indexHtml;
    if (!await file.exists()) {
      return;
    }

    String html = await file.readAsString();

    Map<String, dynamic> currentMap = {'imports': <String, dynamic>{}};
    final existingMatch = _importMapRegex.firstMatch(html);

    if (existingMatch != null) {
      try {
        final content = existingMatch.group(1)!.trim();
        if (content.isNotEmpty) {
          currentMap = jsonDecode(content) as Map<String, dynamic>;
        }
      } catch (_) {
        currentMap = {'imports': <String, dynamic>{}};
      }
    }

    final imports = (currentMap['imports'] is Map)
        ? Map<String, dynamic>.from(currentMap['imports'] as Map)
        : <String, dynamic>{};

    // vendorPath is project-root-relative (e.g. "web/vendor/foo.min.js"), but
    // the dev/build server document root *is* the web/ directory itself
    // (see BloomLiveReloadServer.webDir), so the browser-facing URL must
    // drop the leading "web/" segment or it 404s against a nonexistent
    // "web/web/vendor/..." path.
    final urlPath = vendorPath.startsWith('web/') ? vendorPath.substring(4) : vendorPath;
    imports[packageName] = '/$urlPath';
    currentMap['imports'] = imports;

    final newImportMapJson = const JsonEncoder.withIndent('  ').convert(currentMap);
    final newScriptTag = '<script type="importmap">\n$newImportMapJson\n</script>';

    if (existingMatch != null) {
      html = html.replaceFirst(_importMapRegex, newScriptTag);
    } else {
      if (html.contains('</head>')) {
        html = html.replaceFirst('</head>', '  $newScriptTag\n</head>');
      } else {
        html = '$newScriptTag\n$html';
      }
    }

    // Tailwind's browser build is side-effect-only (no window global to
    // bridge) — give it its own self-executing script instead of the
    // window-global bootstrap block every other package goes through.
    if (packageName == _tailwindBrowserPackage) {
      html = _addTailwindScriptTag(html);
    } else {
      html = _addPackageToBootstrapHtml(html, packageName, jsGlobal);
    }

    await file.writeAsString(html);
  }

  /// Inserts (or leaves alone, if already present) the self-executing
  /// `import '@tailwindcss/browser'` script tag that makes Tailwind's
  /// in-browser JIT engine actually run.
  String _addTailwindScriptTag(String html) {
    if (_tailwindScriptRegex.hasMatch(html)) return html;

    final tag = '<script type="module">\n'
        '// AUTO-GENERATED by bloom_cli (tailwindcss) — runs the in-browser\n'
        '// Tailwind JIT engine, which scans the DOM for utility classes and\n'
        '// injects a <style> tag. Do not edit by hand; regenerated by\n'
        '// `bloom add`/`bloom remove`.\n'
        "import '$_tailwindBrowserPackage';\n"
        '</script>';

    final importMapMatch = _importMapRegex.firstMatch(html);
    if (importMapMatch != null) {
      final endPos = importMapMatch.end;
      return '${html.substring(0, endPos)}\n  $tag${html.substring(endPos)}';
    } else if (html.contains('</head>')) {
      return html.replaceFirst('</head>', '  $tag\n</head>');
    } else {
      return '$tag\n$html';
    }
  }

  /// Removes an entry from the <script type="importmap"> block and bootstrap script in web/index.html.
  Future<void> removeEntry({required String packageName}) async {
    final file = _indexHtml;
    if (!await file.exists()) return;

    String html = await file.readAsString();

    final existingMatch = _importMapRegex.firstMatch(html);
    if (existingMatch != null) {
      Map<String, dynamic> currentMap = {'imports': <String, dynamic>{}};
      try {
        final content = existingMatch.group(1)!.trim();
        if (content.isNotEmpty) {
          currentMap = jsonDecode(content) as Map<String, dynamic>;
        }
      } catch (_) {
        return;
      }

      final imports = (currentMap['imports'] is Map)
          ? Map<String, dynamic>.from(currentMap['imports'] as Map)
          : <String, dynamic>{};

      imports.remove(packageName);
      currentMap['imports'] = imports;

      final newJson = const JsonEncoder.withIndent('  ').convert(currentMap);
      final newScriptTag = '<script type="importmap">\n$newJson\n</script>';

      html = html.replaceFirst(_importMapRegex, newScriptTag);
    }

    if (packageName == _tailwindBrowserPackage) {
      html = html.replaceFirst(_tailwindScriptRegex, '').trimRight();
    } else {
      html = _removePackageFromBootstrapHtml(html, packageName);
    }
    await file.writeAsString(html);
  }

  /// Rebuilds the bootstrap <script type="module"> block in web/index.html from manifest entries.
  Future<void> updateBootstrap(Iterable<NpmManifestEntry> entries) async {
    final file = _indexHtml;
    if (!await file.exists()) return;

    String html = await file.readAsString();
    html = rebuildBootstrapHtml(html, entries);
    await file.writeAsString(html);
  }

  /// Generates the HTML string with the bootstrap block regenerated from entries.
  static String rebuildBootstrapHtml(String html, Iterable<NpmManifestEntry> entries) {
    final eligible = entries.where((e) => e.npmName != '@tailwindcss/browser').toList();
    if (eligible.isEmpty) {
      return html.replaceFirst(_bootstrapRegex, '').trimRight();
    }

    final buffer = StringBuffer();
    buffer.writeln('<script type="module">');
    buffer.writeln('// AUTO-GENERATED by bloom_cli — bridges vendored ESM packages onto');
    buffer.writeln('// window globals so @JS() interop bindings can find them. Do not edit');
    buffer.writeln('// by hand; regenerated by `bloom add`/`bloom npm` commands.');
    for (final entry in eligible) {
      final safeName = safeAlias(entry.npmName);
      final globalName = entry.jsGlobal ?? inferGlobal(entry.npmName);
      buffer.writeln('import * as __bloom_ns_$safeName from \'${entry.npmName}\';');
      buffer.writeln('window.$globalName = __bloom_ns_$safeName;');
    }
    buffer.write('</script>');

    final newBootstrap = buffer.toString();

    if (_bootstrapRegex.hasMatch(html)) {
      return html.replaceFirst(_bootstrapRegex, newBootstrap);
    }

    final importMapMatch = _importMapRegex.firstMatch(html);
    if (importMapMatch != null) {
      final endPos = importMapMatch.end;
      return '${html.substring(0, endPos)}\n  $newBootstrap${html.substring(endPos)}';
    } else if (html.contains('</head>')) {
      return html.replaceFirst('</head>', '  $newBootstrap\n</head>');
    } else {
      return '$newBootstrap\n$html';
    }
  }

  String _addPackageToBootstrapHtml(String html, String packageName, String? jsGlobal) {
    final safeName = safeAlias(packageName);
    final globalName = jsGlobal ?? inferGlobal(packageName);

    final existingBootstrapMatch = _bootstrapRegex.firstMatch(html);
    if (existingBootstrapMatch != null) {
      final blockContent = existingBootstrapMatch.group(0)!;
      if (blockContent.contains("from '$packageName'") || blockContent.contains('from "$packageName"')) {
        // Already present
        return html;
      }
      final closingTag = RegExp(r'<\/script>', caseSensitive: false);
      final closingMatch = closingTag.firstMatch(blockContent);
      if (closingMatch != null) {
        final newBlock = '${blockContent.substring(0, closingMatch.start)}'
            'import * as __bloom_ns_$safeName from \'$packageName\';\n'
            'window.$globalName = __bloom_ns_$safeName;\n'
            '</script>';
        return html.replaceFirst(_bootstrapRegex, newBlock);
      }
    }

    return rebuildBootstrapHtml(html, [
      NpmManifestEntry(
        alias: packageName,
        npmName: packageName,
        version: '',
        vendorFile: '',
        dartBinding: '',
        jsGlobal: globalName,
      ),
    ]);
  }

  String _removePackageFromBootstrapHtml(String html, String packageName) {
    final existingMatch = _bootstrapRegex.firstMatch(html);
    if (existingMatch == null) return html;

    final blockContent = existingMatch.group(0)!;
    final safeName = safeAlias(packageName);

    final lines = blockContent.split('\n');
    final filteredLines = <String>[];
    for (int i = 0; i < lines.length; i++) {
      final line = lines[i];
      if (line.contains("from '$packageName'") ||
          line.contains('from "$packageName"') ||
          line.contains('__bloom_ns_$safeName')) {
        continue;
      }
      filteredLines.add(line);
    }

    final hasImports = filteredLines.any((l) => l.trim().startsWith('import '));
    if (!hasImports) {
      return html.replaceFirst(_bootstrapRegex, '').trimRight();
    }

    final newBlock = filteredLines.join('\n');
    return html.replaceFirst(_bootstrapRegex, newBlock);
  }
}

