// Generated by Bloom Router Scanner. DO NOT EDIT.
import 'package:bloom_framework/bloom.dart';

import '../routes/index.dart';
import '../routes/scan.dart';
import '../routes/session.dart';

List<RouteBase> get $bloomRoutes => [
  BloomRouter.route(
    path: '/',
    builder: (context, match) => const IndexRoute(),
  ),
  BloomRouter.route(
    path: '/scan',
    builder: (context, match) => const ScanRoute(),
  ),
  BloomRouter.route(
    path: '/session',
    builder: (context, match) => SessionRoute(
      uriString: match.queryParameters['uri'],
    ),
  ),
];
