import * as React from 'preact/compat';
import { useState } from 'preact/hooks';
import { ArrowRight, CheckCircle2, Cpu, Layers, Sparkles, Code2, Terminal, ShieldCheck } from 'lucide-preact';
import { highlightDart } from '../../lib/dart-highlighter';

interface Step {
  id: number;
  num: string;
  title: string;
  shortTitle: string;
  description: string;
  details: string[];
  codeSnippet: string;
  badge: string;
}

const steps: Step[] = [
  {
    id: 1,
    num: 'STEP 01',
    title: 'STANDARDIZE',
    shortTitle: 'Standardize Architecture',
    description: 'Establish unified directory conventions, configuration files, and project layout across all Flutter applications.',
    details: [
      'Next.js-inspired `lib/app/routes` directory hierarchy',
      'Unified `bloom.yaml` central environment manifest',
      'Deterministic boot sequence before `runApp()`',
    ],
    codeSnippet: `// lib/app/routes/_layout.dart\nclass RootLayout extends BloomLayout {\n  @override\n  Widget build(BuildContext context, Widget child) {\n    return MainScaffold(body: child);\n  }\n}`,
    badge: 'CONVENTIONS_ENGINE',
  },
  {
    id: 2,
    num: 'STEP 02',
    title: 'WRAP',
    shortTitle: 'Thin Infrastructure Wrappers',
    description: 'Wrap battle-tested Flutter packages (go_router, signals, dio) in zero-boilerplate, type-safe API abstractions.',
    details: [
      'Zero `setState` signals reactivity wrappers',
      'Type-safe route parameter extraction',
      'Scoped dependency injection container',
    ],
    codeSnippet: `// Thin reactive state controller\nclass UserController extends BloomController {\n  final user = signal<User?>(null);\n  late final isLoggedIn = computed(() => user.value != null);\n}`,
    badge: 'ZERO_BOILERPLATE',
  },
  {
    id: 3,
    num: 'STEP 03',
    title: 'GENERATE',
    shortTitle: 'Deterministic Code Generation',
    description: 'Eliminate manual route declaration and boilerplate via real-time AST parsing and instant background code generation.',
    details: [
      'Sub-50ms incremental route table compilation',
      'Auto-generated strongly typed navigation helpers',
      'Zero runtime reflection overhead (AOT safe)',
    ],
    codeSnippet: `// Auto-generated by Bloom CLI\nclass AppRoutes {\n  static const userProfile = '/users/:id';\n  static void goToProfile(BuildContext ctx, {required String id}) =>\n    ctx.go(userProfile, params: {'id': id});\n}`,
    badge: 'AST_COMPILER',
  },
  {
    id: 4,
    num: 'STEP 04',
    title: 'ORCHESTRATE',
    shortTitle: 'Unified DX & CLI Tooling',
    description: 'Single unified CLI orchestrating Dart pub, Flutter build tools, device pairing, and Shorebird OTA releases.',
    details: [
      'Wireless dev pairing with physical mobile devices',
      'Expo-style CLI diagnostic dashboard',
      'Atomic production build artifacts',
    ],
    codeSnippet: `$ bloom dev --device physical-ios\n[+] Paired via Wi-Fi (192.168.1.42:5555)\n[+] Hot reload listening at port 4321\n[+] Impeller 60fps rendering active`,
    badge: 'CLI_ORCHESTRATOR',
  },
  {
    id: 5,
    num: 'STEP 05',
    title: 'REPLACE GAPS',
    shortTitle: 'Native Ecosystem Extensions',
    description: 'Fill critical gaps in the Flutter ecosystem with custom-engineered primitives: Bloom Query, Bloom UI Studio, and Dev Client.',
    details: [
      'Declarative server-state caching & optimistic mutations',
      'shadcn-inspired mobile UI token components',
      'Shorebird cryptographic byte-patching pipeline',
    ],
    codeSnippet: `// Declarative Bloom Query\nfinal userQuery = useBloomQuery(\n  key: 'user_profile',\n  fetcher: () => api.getProfile(),\n  staleTime: Duration(minutes: 5),\n);`,
    badge: 'ECOSYSTEM_GAP_FILL',
  },
];

export function OrchestrationPipeline() {
  const [activeStepId, setActiveStepId] = useState<number>(1);
  const activeStep = steps.find((s) => s.id === activeStepId) || steps[0];

  return (
    <div className="max-w-5xl mx-auto space-y-8">
      {/* Step Selection Pipeline Nodes */}
      <div className="relative">
        {/* Connecting Progress Glow Line */}
        <div className="absolute top-1/2 left-0 right-0 h-0.5 bg-slate-200 dark:bg-zinc-800 -translate-y-1/2 -z-0 hidden md:block" />
        <div 
          className="absolute top-1/2 left-0 h-0.5 bg-gradient-to-r from-purple-500 via-teal-400 to-blue-500 -translate-y-1/2 transition-all duration-500 -z-0 hidden md:block"
          style={{ width: `${((activeStepId - 1) / (steps.length - 1)) * 100}%` }}
        />

        <div className="grid grid-cols-1 sm:grid-cols-3 md:grid-cols-5 gap-3 relative z-10">
          {steps.map((step) => {
            const isActive = step.id === activeStepId;
            const isCompleted = step.id < activeStepId;

            return (
              <button
                key={step.id}
                onClick={() => setActiveStepId(step.id)}
                className={`p-4 rounded-2xl text-left transition-all duration-300 relative group border ${
                  isActive
                    ? 'bg-slate-900 text-white dark:bg-white dark:text-slate-950 border-slate-900 dark:border-white shadow-xl shadow-purple-500/10 scale-105 font-bold'
                    : isCompleted
                    ? 'bg-white/90 dark:bg-zinc-900 text-slate-900 dark:text-slate-100 border-purple-500/40 dark:border-purple-400/40 shadow-sm'
                    : 'bg-white/70 dark:bg-zinc-950 text-slate-600 dark:text-slate-400 border-slate-200 dark:border-zinc-800 hover:border-slate-400 dark:hover:border-zinc-700'
                }`}
              >
                <div className="flex items-center justify-between mb-2">
                  <span className={`text-[10px] font-mono font-bold tracking-widest ${
                    isActive ? 'text-purple-300 dark:text-purple-600' : 'text-slate-400'
                  }`}>
                    {step.num}
                  </span>
                  {isCompleted ? (
                    <CheckCircle2 className="w-3.5 h-3.5 text-purple-500" />
                  ) : (
                    <div className={`w-2 h-2 rounded-full ${isActive ? 'bg-purple-400 animate-pulse' : 'bg-slate-300 dark:bg-zinc-700'}`} />
                  )}
                </div>
                <div className="text-xs font-black tracking-tight uppercase">
                  {step.title}
                </div>
              </button>
            );
          })}
        </div>
      </div>

      {/* Active Step Detailed Card */}
      <div className="p-8 sm:p-10 rounded-3xl bg-white dark:bg-black backdrop-blur border border-slate-200 dark:border-zinc-800 shadow-2xl relative overflow-hidden transition-all duration-500">
        <div className="absolute top-0 right-0 w-80 h-80 bg-purple-500/5 rounded-full blur-3xl pointer-events-none" />

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start relative z-10">
          {/* Left Description & Bullet Highlights */}
          <div className="lg:col-span-6 space-y-5">
            <div className="flex items-center gap-2">
              <span className="px-3 py-1 rounded-full bg-purple-500/10 text-purple-600 dark:text-purple-400 text-xs font-mono font-bold border border-purple-500/20">
                {activeStep.badge}
              </span>
              <span className="text-xs font-mono font-bold text-slate-400">
                Step {activeStep.id} of 5
              </span>
            </div>

            <h3 className="text-2xl sm:text-3xl font-black tracking-tight text-slate-900 dark:text-white">
              {activeStep.shortTitle}
            </h3>

            <p className="text-sm sm:text-base text-slate-600 dark:text-slate-300 leading-relaxed font-normal">
              {activeStep.description}
            </p>

            <ul className="space-y-2.5 pt-2">
              {activeStep.details.map((detail, idx) => (
                <li key={idx} className="flex items-start gap-2.5 text-xs sm:text-sm text-slate-700 dark:text-slate-200 font-medium">
                  <CheckCircle2 className="w-4 h-4 text-purple-500 flex-shrink-0 mt-0.5" />
                  <span>{detail}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Right Live Code Sandbox */}
          <div className="lg:col-span-6">
            <div className="rounded-2xl overflow-hidden bg-slate-950 dark:bg-black border border-slate-800 dark:border-zinc-800 shadow-xl font-mono text-xs">
              <div className="flex items-center justify-between px-4 py-3 bg-slate-900 dark:bg-zinc-950 border-b border-slate-800 dark:border-zinc-800">
                <div className="flex items-center gap-2">
                  <div className="w-2.5 h-2.5 rounded-full bg-rose-500/80" />
                  <div className="w-2.5 h-2.5 rounded-full bg-amber-500/80" />
                  <div className="w-2.5 h-2.5 rounded-full bg-emerald-500/80" />
                </div>
                <span className="text-[11px] text-slate-400 font-bold">{activeStep.num} — {activeStep.title}</span>
              </div>
              <pre
                className="p-5 text-slate-100 leading-relaxed overflow-x-auto font-mono text-xs"
                dangerouslySetInnerHTML={{ __html: highlightDart(activeStep.codeSnippet) }}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
